<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flora@Home API
 *
 * Flora@Home enables any web shop to sell a range of fresh flowers and plants. Completely integrated into your own web shop. Our REST API allows you to request your own assortment. The API makes a two-way traffic between applications and webshops possible.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: api_support@floraathome.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class */
// * @description Properties not marked with the red asterisk can contain an empty string
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "productcode"
     */
    public function testPropertyProductcode()
    {
    }

    /**
     * Test attribute "potsize"
     */
    public function testPropertyPotsize()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "dutchname"
     */
    public function testPropertyDutchname()
    {
    }

    /**
     * Test attribute "linnaeusname"
     */
    public function testPropertyLinnaeusname()
    {
    }

    /**
     * Test attribute "numberperorder"
     */
    public function testPropertyNumberperorder()
    {
    }

    /**
     * Test attribute "purchaseprice"
     */
    public function testPropertyPurchaseprice()
    {
    }

    /**
     * Test attribute "promotionaltext"
     */
    public function testPropertyPromotionaltext()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "specifications"
     */
    public function testPropertySpecifications()
    {
    }

    /**
     * Test attribute "caretips"
     */
    public function testPropertyCaretips()
    {
    }

    /**
     * Test attribute "aboutgrower"
     */
    public function testPropertyAboutgrower()
    {
    }

    /**
     * Test attribute "branches"
     */
    public function testPropertyBranches()
    {
    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {
    }

    /**
     * Test attribute "grower"
     */
    public function testPropertyGrower()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }
}
